
default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 25
  username: <%= ENV["DB_USER_NAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: payment_system

test:
  <<: *default
  database: payment_system_test

production:
  <<: *default
  database: payment_system_production
  username: payment_system
  password: <%= ENV["PAYMENT_SYSTEM_DATABASE_PASSWORD"] %>
